#  --------------------------------------------------------
#  Karnak Application Profiles
#  --------------------------------------------------------
name: dev-YAML
environment: LOCAL
karnakadmin: ${KARNAK_ADMIN}
karnakpassword: ${KARNAK_PASSWORD}
mainzelliste:
  apikey: '${MAINZELLISTE_API_KEY}'
  serverurl: 'http://${MAINZELLISTE_HOSTNAME}:${MAINZELLISTE_HTTP_PORT}'
  idtypes: '${MAINZELLISTE_ID_TYPES}'
dcmprofile:
  hmackey: '${KARNAK_HMAC_KEY}'
logging:
  level:
    com:
      zaxxer: INFO
    org:
      atmosphere: WARN
      dcm4che3:
        net: INFO
      hibernate: WARN
      springframework: INFO
      springframework.core.io.support: INFO
      weasis: DEBUG
      karnak: DEBUG
    root: INFO
server:
  port: 8081
spring:
  profiles:
    active: '@activatedProperties@'
  datasource:
    password: ${DB_PASSWORD}
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: ${DB_USER}
    hikari:
      leak-detection-threshold: 2000
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      # First time to create the db the value must be: create
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true
