#  --------------------------------------------------------
#  Karnak Application Profiles
#  --------------------------------------------------------
name: dev-YAML
environment: LOCAL
mainzelliste:
  apikey: 'changeThisApiKey'
  serverurl: 'http://localhost:8083'
  idtypes: 'pid'
dcmprofile:
  hmackey: 'undefined'
logging:
  level:
    com:
      zaxxer: INFO
    org:
      atmosphere: WARN
      dcm4che3:
        net: INFO
      hibernate: WARN
      springframework: INFO
      springframework.core.io.support: INFO
      weasis: DEBUG
      karnak: DEBUG
    root: INFO
  pattern:
    console: '%-5level %logger{36} - %msg%n'
server:
  port: 8088
spring:
  profiles:
    active: '@activatedProperties@'
  datasource:
    password: ${KARNAK_PG_PASSWORD}
    url: 'jdbc:postgresql://localhost:${KARNAK_PG_PORT}/${KARNAK_PG_DB}'
    username: ${KARNAK_PG_USER}
    hikari:
      leak-detection-threshold: 2000
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      # First time to create the db the value must be: create
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true
