version: "3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=PleasePutASafePasswordHere
    ports:
      - 5444:5432
    volumes:
      - db-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    volumes:  
      - ./mainzelliste/mainzelliste.conf:/mainzelliste.conf.default
    ports:
      - "8083:8080"
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_PASS=PleasePutASafePasswordHere
      - ML_API_KEY=changeThisApiKey
    depends_on:
      - db
  postgresidp:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: karnak
      POSTGRES_USER: karnak
      POSTGRES_PASSWORD: 5!KAnN@%98%d
    ports:
      - 5433:5432
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
  
volumes:
  db-scripts:
  db-data:
  karnak-db-data:
