version: "3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=PleasePutASafePasswordHere
    ports:
      - ${MAINZELLISTE_PG_PORT}:5432
    volumes:
      - db-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    volumes:  
      - ./mainzelliste/mainzelliste.conf:/mainzelliste.conf.default
    ports:
      - ${MAINZELLISTE_WEB_PORT}:8080
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_PASS=PleasePutASafePasswordHere
      - ML_API_KEY=changeThisApiKey
    depends_on:
      - db
  postgresidp:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: ${KARNAK_PG_DB}
      POSTGRES_USER: ${KARNAK_PG_USER}
      POSTGRES_PASSWORD: ${KARNAK_PG_PASSWORD}
    ports:
      - ${KARNAK_PG_PORT}:5432
    volumes:
      - karnak-db-data:/var/lib/postgresql/data

volumes:
  db-scripts:
  db-data:
  karnak-db-data:
