version: '3.7'

services:
  karnak:
    container_name: karnak
    image: osirixfoundation/karnak-mvc:5.0.0-SNAPSHOT
    ports:
      - "${GAT_IN_PORT}:11115"
      - "${GAT_OUT_PORT}:11119"
      - "${WEB_ADMIN}:8081"
    env_file: karnak.env
    volumes:
    # - ./destination:/var/lib/karnak
  postgresidp:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:5432
    volumes:
      - ${VSVOLUME_NAME}:/var/lib/postgresql/data