version: '3.7'

services:
  karnak:
    image: karnak-hardcoded:latest
    ports:
      - "${DICOM_LISTENER_PORT}:11119"
      - "${KARNAK_WEB_PORT}:8088"
    env_file: karnak.env
    depends_on:
      - karnak-db
    secrets:
      - postgres_karnak_password
      - mainzellisteApiKey
    #volumes:
    # - ./destination:/var/lib/karnak

  karnak-db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=karnak
      - POSTGRES_USER=karnak
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_karnak_password
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
    secrets:
      - postgres_karnak_password

  mainzelliste-db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD_FILE=/run/secrets/mainzellisteDbPassword
    volumes:
      - mainzelliste-db-data:/var/lib/postgresql/data
    secrets:
      - mainzellisteDbPassword

  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    volumes:
      - ./mainzelliste/mainzelliste.conf:/mainzelliste.conf.default
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_HOST=mainzelliste-db
    secrets:
      - mainzellisteDbPassword
      - mainzellisteApiKey
    depends_on:
      - mainzelliste-db

secrets:
  postgres_karnak_password:
    file: secrets/karnak_postgres_password
  mainzellisteDbPassword:
    file: secrets/mainzelliste_postgres_password
  mainzellisteApiKey:
    file: secrets/mainzelliste_api_key

volumes:
  mainzelliste-db-data:
  karnak-db-data: