version: '3.7'

services:
  karnak:
    image: docker.io/library/karnak-mvc:5.0.0-SNAPSHOT
    ports:
      - "${DICOM_LISTENER_PORT}:11119"
      - "${KARNAK_WEB_PORT}:8081"
    env_file: karnak.env
    depends_on:
      - karanak-psql
    #volumes:
    # - ./destination:/var/lib/karnak
  mainzelliste-psql:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=PleasePutASafePasswordHere
    ports:
      - 5444:5432
    volumes:
      - db-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    volumes:
      - ./mainzelliste/mainzelliste.conf:/mainzelliste.conf.default
    ports:
      - "8083:8080"
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_PASS=PleasePutASafePasswordHere
      - ML_API_KEY=changeThisApiKey
    depends_on:
      - mainzelliste-psql
  karanak-psql:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: ${KARNAK_PG_DB}
      POSTGRES_USER: ${KARNAK_PG_USER}
      POSTGRES_PASSWORD: ${KARNAK_PG_PASSWORD}
    ports:
      - ${KARNAK_PG_PORT}:5432
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
volumes:
  db-scripts:
  db-data:
  karnak-db-data: